"""add_project_and_parent_id_to_tasks

Revision ID: a26bb481b78b
Revises: bdb085160b3d
Create Date: 2026-04-02 18:34:12.100889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26bb481b78b'
down_revision: Union[str, None] = 'bdb085160b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_project'), 'tasks', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'project')
    # ### end Alembic commands ###
