"""Add agent_logs table for CLI event persistence

Revision ID: f96067e43c25
Revises: a26bb481b78b
Create Date: 2026-04-02 21:40:47.558316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96067e43c25'
down_revision: Union[str, None] = 'a26bb481b78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_id'), 'agent_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_task_id'), 'agent_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_timestamp'), 'agent_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_timestamp'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_task_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
